fix: improve in Service page and portfolio page Loading

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -8,7 +8,7 @@ npm run check-types || {
     Are you seriously trying to write that? Make the changes required above.'
     false;
 }
-npx lint-staged 
+npx lint-staged -p false
 # #Check Prettier standards
 # npm run check-format || {
 #     echo '😂🤮Its Raw - Your styling looks disgusting😂🤮
@@ -25,11 +25,11 @@ npx lint-staged
 #     echo '😂... Alright... Code looks good to me.. Trying to build now. 😂'
 
 
-# npm run build || {
-#     echo '❌⚒️💡 Better call to your Senior... Because your build failed ❌⚒️💡
-#     Next build Failed: View the erros above to see why.'
-#     false
-# }
+npm run build || {
+    echo '❌⚒️💡 Better call to your Senior... Because your build failed ❌⚒️💡
+    Next build Failed: View the erros above to see why.'
+    false
+}
 
 echo '😂... Alright... Code looks good to me.. Lets Commit it. 😂'
 
